/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SupportTicket } from "./SupportTicket";
import { SupportTicketCountArgs } from "./SupportTicketCountArgs";
import { SupportTicketFindManyArgs } from "./SupportTicketFindManyArgs";
import { SupportTicketFindUniqueArgs } from "./SupportTicketFindUniqueArgs";
import { CreateSupportTicketArgs } from "./CreateSupportTicketArgs";
import { UpdateSupportTicketArgs } from "./UpdateSupportTicketArgs";
import { DeleteSupportTicketArgs } from "./DeleteSupportTicketArgs";
import { Customer } from "../../customer/base/Customer";
import { SupportAgent } from "../../supportAgent/base/SupportAgent";
import { SupportTicketService } from "../supportTicket.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SupportTicket)
export class SupportTicketResolverBase {
  constructor(
    protected readonly service: SupportTicketService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SupportTicket",
    action: "read",
    possession: "any",
  })
  async _supportTicketsMeta(
    @graphql.Args() args: SupportTicketCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SupportTicket])
  @nestAccessControl.UseRoles({
    resource: "SupportTicket",
    action: "read",
    possession: "any",
  })
  async supportTickets(
    @graphql.Args() args: SupportTicketFindManyArgs
  ): Promise<SupportTicket[]> {
    return this.service.supportTickets(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SupportTicket, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SupportTicket",
    action: "read",
    possession: "own",
  })
  async supportTicket(
    @graphql.Args() args: SupportTicketFindUniqueArgs
  ): Promise<SupportTicket | null> {
    const result = await this.service.supportTicket(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SupportTicket)
  @nestAccessControl.UseRoles({
    resource: "SupportTicket",
    action: "create",
    possession: "any",
  })
  async createSupportTicket(
    @graphql.Args() args: CreateSupportTicketArgs
  ): Promise<SupportTicket> {
    return await this.service.createSupportTicket({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        supportAgent: args.data.supportAgent
          ? {
              connect: args.data.supportAgent,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SupportTicket)
  @nestAccessControl.UseRoles({
    resource: "SupportTicket",
    action: "update",
    possession: "any",
  })
  async updateSupportTicket(
    @graphql.Args() args: UpdateSupportTicketArgs
  ): Promise<SupportTicket | null> {
    try {
      return await this.service.updateSupportTicket({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          supportAgent: args.data.supportAgent
            ? {
                connect: args.data.supportAgent,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SupportTicket)
  @nestAccessControl.UseRoles({
    resource: "SupportTicket",
    action: "delete",
    possession: "any",
  })
  async deleteSupportTicket(
    @graphql.Args() args: DeleteSupportTicketArgs
  ): Promise<SupportTicket | null> {
    try {
      return await this.service.deleteSupportTicket(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async getCustomer(
    @graphql.Parent() parent: SupportTicket
  ): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => SupportAgent, {
    nullable: true,
    name: "supportAgent",
  })
  @nestAccessControl.UseRoles({
    resource: "SupportAgent",
    action: "read",
    possession: "any",
  })
  async getSupportAgent(
    @graphql.Parent() parent: SupportTicket
  ): Promise<SupportAgent | null> {
    const result = await this.service.getSupportAgent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
